source "https://rubygems.org"

gem 'sinatra'
gem 'rerun', github: 'alexch/rerun'
gem 'sqlite3'
gem 'byebug'
gem 'slim'
gem 'bcrypt'
gem 'bootstrap'
gem 'byebug'
gem 'oauth2'
#gem 'base64'
gem 'httparty'
gem 'json'
#gem 'rubygems'
